services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HOST_PORT}:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "128M"
    restart: always
